linter-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/prskr/git-age
    sections:
      - standard
      - default
      - prefix(github.com/prskr/git-age)
      - alias
      - blank
      - dot
    custom-order: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/prskr/git-age
  golint:
    min-confidence: 0
  importas:
    no-unaliased: true
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - gosec
    - interfacebloat
    # - intrange
    - lll
    - maintidx
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - sloglint
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - err113
        - funlen
        - cyclop
        - gocognit
        - gochecknoinits
        - gochecknoglobals

run:
  skip-files: [ ]
  modules-download-mode: readonly
  timeout: 5m
