version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - maintidx
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - sloglint
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    importas:
      no-unaliased: true
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - dupl
          - err113
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - gocognit
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/prskr/git-age)
        - alias
        - blank
        - dot
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/prskr/git-age
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
