version: 1

before:
  hooks:
    - go mod tidy -go=1.21
    - mkdir -p out/man
    - mkdir -p out/html
    - asciidoctor -a reproducible -b manpage -o out/man/git-age.1 docs/git-age.adoc
    - gzip out/man/git-age.1
    - asciidoctor -a reproducible -b html5 -o out/html/git-age.html docs/git-age.adoc

builds:
  - env:
      - CGO_ENABLED=0
    binary: git-age
    ldflags:
      - '-s -w -X github.com/prskr/git-age/handlers/cli.version={{.Version}} -X github.com/prskr/git-age/handlers/cli.commit={{.Commit}} -X github.com/prskr/git-age/handlers/cli.date={{.Date}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: out/man/git-age.1.gz
        dst: docs/git-age.1.gz

sboms:
  - artifacts: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: git-age
    homepage: https://github.com/prskr/git-age
    maintainer: Peter Kurfer <peter.kurfer@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    contents:
      - src: out/man/git-age.1.gz
        dst: /usr/share/man/man1/git-age.1.gz
      - src: LICENSE
        dst: /usr/share/licenses/git-age/LICENSE

brews:
  - name: git-age
    homepage: https://github.com/prskr/git-age
    description: |-
      git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: auto
    folder: Formula
    dependencies:
      - name: git
        os: mac
    extra_install: |
      man1.install "docs/git-age.1.gz"
    test: |
      system "#{bin}/git-age --help"
    repository:
      owner: prskr
      name: the-prancing-package
      token: "{{ .Env.GH_TAP_PAT }}"
      pull_request:
        enabled: true

winget:
  - name: git-age
    publisher: prskr
    short_description: |-
      git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently
    license: mit
    homepage: https://github.com/prskr/git-age
    publisher_support_url: "https://github.com/prskr/git-age/issues/new"
    package_identifier: prskr.git-age
    url_template: "https://github.com/prskr/git-age/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"
    license_url: "https://raw.githubusercontent.com/prskr/git-age/main/LICENSE"
    release_notes: "{{.Changelog}}"
    tags:
      - git
      - age
      - cli
      - encryption
    repository:
        owner: prskr
        name: winget-pkgs
        branch: "git-age-{{.Version}}"
        token: "{{ .Env.GH_WINGET_PAT_TOKEN }}"
        pull_request:
          enabled: true
          draft: true
          base:
            owner: microsoft
            name: winget-pkgs
            branch: master