version: 2

before:
  hooks:
    - rm -rf out/man
    - mkdir -p out/man
    - mkdir -p out/html
    - asciidoctor -a reproducible -b manpage -o out/man/git-age.1 docs/man/git-age.adoc
    - gzip out/man/git-age.1
    - asciidoctor -a reproducible -b html5 -o out/html/git-age.html docs/man/git-age.adoc

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
    binary: git-age
    ldflags:
      - "-s -w -X github.com/prskr/git-age/handlers/cli.Version={{.Tag}} -X github.com/prskr/git-age/handlers/cli.Commit={{.Commit}} -X github.com/prskr/git-age/handlers/cli.Date={{.Date}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: out/man/git-age.1.gz
        dst: docs/git-age.1.gz
      - LICENSE

sboms:
  - artifacts: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: git_age
    package_name: git-age
    homepage: https://github.com/prskr/git-age
    maintainer: Peter Kurfer <peter.kurfer@gmail.com>
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
    contents:
      - src: out/man/git-age.1.gz
        dst: /usr/share/man/man1/git-age.1.gz
      - src: LICENSE
        dst: /usr/share/licenses/git-age/LICENSE

    rpm:
      signature:
        key_file: '{{ envOrDefault "GITHUB_WORKSPACE" "." }}/.gnupg/gpg.key'
    deb:
      signature:
        key_file: '{{ envOrDefault "GITHUB_WORKSPACE" "." }}/.gnupg/gpg.key'

brews:
  - name: git-age
    homepage: https://github.com/prskr/git-age
    description: |-
      git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update {{ .ProjectName }} to version {{ .Tag }}"
    skip_upload: auto
    directory: Formula
    dependencies:
      - name: git
        os: mac
    extra_install: |
      man1.install "docs/git-age.1.gz"
    test: |
      system "#{bin}/git-age --help"
    repository:
      owner: prskr
      name: homebrew-the-prancing-package
      token: "{{ .Env.GH_TAP_PAT }}"
      pull_request:
        enabled: true

scoops:
  - commit_msg_template: "chore: update {{ .ProjectName }} to version {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    license: "MIT"
    directory: bucket
    homepage: https://github.com/prskr/git-age
    depends: ["git"]
    repository:
      owner: prskr
      name: scoop-the-prancing-package
      token: "{{ .Env.GH_SCOOP_PAT }}"
      pull_request:
        enabled: true
        base:
          owner: prskr
          name: scoop-the-prancing-package
          branch: main

winget:
  - name: git-age
    publisher: prskr
    short_description: |-
      git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently
    license: mit
    homepage: https://github.com/prskr/git-age
    publisher_support_url: "https://github.com/prskr/git-age/issues/new"
    package_identifier: prskr.git-age
    url_template: "https://github.com/prskr/git-age/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update {{ .ProjectName }} to version {{ .Tag }}"
    license_url: "https://raw.githubusercontent.com/prskr/git-age/main/LICENSE"
    release_notes: "{{.Changelog}}"
    tags:
      - git
      - age
      - cli
      - encryption
    repository:
      owner: prskr
      name: winget-pkgs
      branch: "git-age-{{.Version}}"
      token: "{{ .Env.GH_WINGET_PAT }}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

aurs:
  - name: git-age-bin
    homepage: https://github.com/prskr/git-age
    description: |
      git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently
    maintainers:
      - "Peter Kurfer <peter.kurfer@gmail.com>"
    contributors:
      - "Peter Kurfer <peter.kurfer@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/git-age-bin.git"
    provides:
      - git-age
    optdepends:
      - git
    package: |-
      # bin
      install -Dm755 "./git-age" "${pkgdir}/usr/bin/git-age"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/git-age/LICENSE"

      # man pages
      install -Dm644 "./docs/git-age.1.gz" "${pkgdir}/usr/share/man/man1/git-age.1.gz"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update to {{ .Tag }}"
