[hooks]

# git hook pre commit
pre-commit = [
    "go mod tidy -go=1.25",
    "go tool husky lint-staged",
    "golangci-lint run",
]

# git hook commit msg
commit-msg = [
    "go tool husky lint-commit",
]

# list staged files do some pre-process and git add
[lint-staged]
"*.go" = [
    "go tool goimports -l -w",
    "go tool gofumpt -l -w",
]
